### ISSUE TITLE
Define license

### ISSUE THREAD

**Issue by paazmaya** [75lb/handlebars-string#1]
Which license is used in this project?

Once decided, add it to `package.json`, by using https://docs.npmjs.com/files/package.json#license property.

Possibly publish a new version to npm which has the license defined, as a bug fix release.

Thank you and here is some 🍇

**Comment by paazmaya** [comment]
Related to https://github.com/75lb/handlebars-array/issues/1 https://github.com/75lb/handlebars-comparison/issues/1 https://github.com/75lb/handlebars-json/issues/1  https://github.com/75lb/handlebars-regexp/issues/1 

If for example MIT is fine, I could open Pull Request in each of these repositories which adds a LICENSE file, adds the license property in package.json and mentions in README.md?

**Comment by 75lb** [comment]
hi, yes send PRs if you like but i won't be free to update the npm packages for another few hours.. and thanks for the unicode fruits ;)

**Comment by 75lb** [comment]
FYI, this is fixed in [jsdoc2md v2](https://github.com/jsdoc2md/jsdoc-to-markdown/releases) which i've updated to no longer use any of the modules mentioned above.. if you like, i'll fix it in v1 too later on tonight.

**Comment by paazmaya** [comment]
Thank you.

Some of my dependencies are using these, hence would need all these handlebars projects to have licenses.

**Comment by 75lb** [comment]
all merged and released, thanks
